// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NewFile() {
  return window['go']['main']['App']['NewFile']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function RequestSave() {
  return window['go']['main']['App']['RequestSave']();
}

export function RequestSaveAs() {
  return window['go']['main']['App']['RequestSaveAs']();
}

export function Save(arg1) {
  return window['go']['main']['App']['Save'](arg1);
}

export function SaveAs(arg1) {
  return window['go']['main']['App']['SaveAs'](arg1);
}
