// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NewFile() {
  return window['go']['main']['App']['NewFile']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}
