// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenConfigFile() {
  return window['go']['main']['AppConfig']['OpenConfigFile']();
}

export function ReadConfig(arg1) {
  return window['go']['main']['AppConfig']['ReadConfig'](arg1);
}
